### ISSUE TITLE
(Smal fix) Can't install: Project name field in pyproject.toml doesn't follow pep0508

### ISSUE THREAD

**Issue by stuaxo** [andytwoods/mrbenn#10]
https://peps.python.org/pep-0508/

I tried submitting a PR a couple of times, but I guess github is not happy today -

Installing locally with `pip install -e .` or `python setup.py develop` both failed, complaining about the name field

Lower casing the name, and replacing spaces with hyphens meant installation ran to completion.

```
$ pip install -e .
Obtaining file:///home/stu/projects/external/mrbenn
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [46 lines of output]
      configuration error: `project.name` must be pep508-identifier
      DESCRIPTION:
          The name (primary identifier) of the project. MUST be statically defined.
      
      GIVEN VALUE:
          "MrBenn Toolbar Plugin"
      
      OFFENDING RULE: 'format'
      
      DEFINITION:
          {
              "type": "string",
              "format": "pep508-identifier"
          }

...
```

**Comment by andytwoods** [comment]
Can you have a other go with creating a pull request. Will avoid potential errors. Thanks

**Comment by stuaxo** [comment]
Yeah it's weird - all the times I was trying from the github GUI.   I'll try pushing up a branch tomorrow.

![image](https://github.com/andytwoods/mrbenn/assets/179677/f041e28b-5df5-469a-aa3e-3da9361be22d)

**Comment by andytwoods** [comment]
> 

i've just pushed this name change. Thanks for spotting.

**Comment by andytwoods** [comment]
released v2. No probs my end now.

**Comment by stuaxo** [comment]
Cheers, I'll pull this - no idea what was going on.
