### ISSUE TITLE
Add project to the toolbar's third party panels list

### ISSUE THREAD

**Issue by tim-schilling** [andytwoods/mrbenn#6]
The toolbar has a list of 3rd party panels in the docs. This can be listed there: https://django-debug-toolbar.readthedocs.io/en/latest/panels.html#third-party-panels

**Comment by robertispas** [comment]
Hey @tim-schilling,

Thank you for letting us know! Will update it shortly!

I'm going to leave this open until the panel is in their docs!

Thank you again for letting us know!

Robert

**Comment by robertispas** [comment]
Link to the PR: https://github.com/jazzband/django-debug-toolbar/pull/1554

**Comment by tim-schilling** [comment]
This was merged in. Thanks for the neat tool and growing the toolbar ecosystem!
