### ISSUE TITLE
opensource license please

### ISSUE THREAD

**Issue by andytwoods** [andytwoods/mrbenn#7]
@robertispas you cool in seeing what license django-debug-toolbar has and adding here? cheers.

**Comment by robertispas** [comment]
Hey,

@andytwoods all sorted! Also added some fancy badges! Would you mind updating the project description and add a link to readthedocs?

Cheers!

**Comment by andytwoods** [comment]
Those badges are awesome! Will get around to these mods hopefully tomorrow :)
