### ISSUE TITLE
Does this use 3.8 features (could it work under 3.7)

### ISSUE THREAD

**Issue by stuaxo** [andytwoods/mrbenn#9]
I've joined a project that (currently) only goes as high as 3.7, could this work there ?

```
$ pip install mrbenn-toolbar-plugin
ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement mrbenn-toolbar-plugin (from versions: none)
ERROR: No matching distribution found for mrbenn-toolbar-plugin
```

**Comment by andytwoods** [comment]
I cant think of any reason why it wouldn't work.

**Comment by stuaxo** [comment]
All these times I was trying editing from the github GUI.

I'll try pushing my local copy up tomorrow.

![image](https://github.com/andytwoods/mrbenn/assets/179677/e9c174c9-2b99-4a51-b2d9-42b61a8545f9)

**Comment by andytwoods** [comment]
just an update. The test suite includes v3.7. Should should be fine.
